# Generated by Django 5.1.2 on 2024-10-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiatours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tours',
            new_name='Tour',
        ),
    ]
